[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = "0.26.1"
tungstenite = "0.26.1"
futures = "0.3"
futures-util = "0.3"
anyhow = "1.0.95"
